### ISSUE TITLE
HBaseSource.scala won't compile

### ISSUE THREAD

**Issue by ans-4175** [luzhuomi/scalding-hbase#2]
Hey, I copied your HBaseSource class and import necessary dependencies in build.sbt. But I got this problem
[error] /home/ans4175/activator/scala-hbase/src/main/scala/com/scalding/HBaseSource.scala:51: method createTap in class Source is accessed from super. It may not be abstract unless it is overridden by a member declared `abstract' and `override'
[error]       case _ => super.createTap(readOrWrite)(mode)
[error]                       ^
[error] one error found

Any suggestion ?
I am using Scala 2.10 and Scalding 2.5.5

**Comment by luzhuomi** [comment]
Hi, are you able to send me a smallish project with build.sbt which exhibits the problem?

**Comment by ans-4175** [comment]
I just want to compile HBaseSource class first. So I add these dependencies
into build.sbt
name := """scala-hbase"""

version := "1.0"

//scalaVersion := "2.11.2"
scalaVersion := "2.10.4"

/* HBase dependencies */
resolvers ++= Seq(
  "Apache Repo"   at "
https://repository.apache.org/content/repositories/releases",
  "Thrift-Repo"   at "http://people.apache.org/~rawson/repo",
  "Sonatype OSS Repo" at "
https://oss.sonatype.org/content/repositories/releases",
  "Twitter Maven" at "http://maven.twttr.com",
  "MVN Repo" at "http://mvnrepository.com/artifact",
  "Concurrent Maven Repo" at "http://conjars.org/repo",
  "releases"      at "http://scala-tools.org/repo-releases"
)

// Hbase 0.94 / Hadoop 2.2.0
libraryDependencies ++= Seq(
    //"org.apache.zookeeper" % "zookeeper" % "3.4.6",
    //"org.specs2" %% "specs2" % "2.4.5" % "test",
    "org.apache.hadoop"       % "hadoop-core"         % "1.2.1",
      "org.apache.hbase"        % "hbase"               % "0.94.16",
      "cascading" % "cascading-core" % "2.1.6",
      "cascading" % "cascading-local" % "2.1.6",
      "cascading" % "cascading-hadoop" % "2.1.6",
      "com.twitter"    %% "scalding-args"  % "0.12.0",
      "com.twitter"    %% "scalding-core"  % "0.12.0",
      "com.twitter"    %% "scalding-date"  % "0.12.0"
)
// Uncomment to use Akka
//libraryDependencies += "com.typesafe.akka" % "akka-actor" % "2.3.3"
//libraryDependencies ~= { _.map(_.exclude("org.slf4j", "slf4j-log4j12")) }

Then I add your HBaseSource.scala file, alongside same package with this
class in separate file, pastebin.com/YVDDKGuh

On Tue, Jan 13, 2015 at 8:59 AM, Kenny Lu <notifications@github.com> wrote:

> Hi, are you able to send me a smallish project with build.sbt which
> exhibits the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luzhuomi/scalding-hbase/issues/2#issuecomment-69683643>
> .
>



-- 
Ahmad Anshorimuslim Syuhada
Teknik Informatika ITB - Web Developer - Linux Enthusiast
+6285224752182 - @ans4175
"trust me I'm [already] an engineer"

**Comment by luzhuomi** [comment]
It's due to the upgrade from scalding core from 0.8.x to 0.12.x. I've checked in the fix.

**Comment by luzhuomi** [comment]
Hi

Sorry for the late reply.

I do see the compilation errors. However, ...

By looking at your source code, I don't see why you need to use my library
Scalding-Hbase, which is meant for writing Scalding job for Hbase tables.
Your example code does not require any use of the Scalding DSL at all.

Regards,
Kenny
